### ISSUE TITLE
Implementar pontuação

### ISSUE THREAD

**Issue by patrickpissurno** [patrickpissurno/rummikub#13]
### Valor das pedras
- Cada pedra vale o número de pontos na sua face (ex.: Pedra 1 vale 1)
- O Coringa vale 30

### Vitória padrão
- A pontuação do vencedor é o módulo da soma da pontuação de todos os perdedores
- A pontuação de cada perdedor é o módulo negativo do somatório de todas as pedras em sua mão

### Vitória alternativa
- A pontuação do vencedor é o módulo da soma da pontuação de todos os perdedores
- A pontuação de cada perdedor é o módulo negativo do somatório de todas as pedras em sua mão, descontado do somatório de pedras na mão do vencedor

**Comment by LucianoHanna** [comment]
Começo: 21:45

**Comment by LucianoHanna** [comment]
Término: 22:10

**Comment by LucianoHanna** [comment]
Recomeço: 22:25

**Comment by LucianoHanna** [comment]
Término: 23:05
