### ISSUE TITLE
Movimentação (lógica) das pedras de um conjunto para outro (seja mesa-mesa ou mão-mesa)

### ISSUE THREAD

**Issue by patrickpissurno** [patrickpissurno/rummikub#22]
- Movimentação de um conjunto para outro (incluso split para 3 conjuntos - 1 com a peça retirada do meio e 2 com os extremos)
- O jogador pode mover qualquer peça da mesa para formar Grupos ou Sequências em **combinação com suas peças da mão**
- Todas as peças movidas devem ser usadas na mesma jogada (não pode malocar peças)

**Comment by LucianoHanna** [comment]
Começo: 18:27

**Comment by LucianoHanna** [comment]
Término: 19:03
